# Generated by Django 4.1.7 on 2023-03-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("number", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
