# Generated by Django 4.1.7 on 2023-04-01 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
