# Generated by Django 4.1.7 on 2023-05-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_alter_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkinglot",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="lot_images"),
        ),
        migrations.AlterField(
            model_name="slot",
            name="position",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
