# Generated by Django 4.1.7 on 2023-05-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0004_alter_booking_take_away_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkinglot",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
