# Generated by Django 4.1.7 on 2023-05-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0007_feedback"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="comments",
            new_name="comment",
        ),
    ]
