# Generated by Django 4.1.7 on 2023-05-22 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0010_review_title_alter_review_comment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_created=True, auto_now=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                ("title", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("image", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.TextField(
                default="fKXvOB0sCKyxQhgB7_LoUr:APA91bH-k0Yanph-DUr9hq4w2lmsWDjrPfoVdQcL1F_DGBDNTBMHeTNVY3YQmByho-rCmttrrL6SXIgZrYH56NKpQSmJPULhPLZhMroEEbG5xnDdf60RGqFp8EGy0bteYwaMQpcLOfEw"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Notifications",
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
