# Generated by Django 4.1.7 on 2023-06-16 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0011_notification_user_fcm_token_delete_notifications_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="lot",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_id",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="booking",
            field=models.OneToOneField(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="webapp.booking",
            ),
            preserve_default=False,
        ),
    ]
