from .booking_serializer import BookingSerializer,SlotBookingSerializer
from .location_serializer import LocationSerializer
from .parking_lot_serializer import ParkingLotSerializer
from .user_serializer import UserSerializer
from .slot_serializer import SlotSerializer
